# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of camera')),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True, verbose_name='Longitude of camera location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True, verbose_name='Latitude of camera location')),
                ('streamUrl', models.URLField(verbose_name='Camera stream url')),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(default='~/graph.pb', max_length=250, verbose_name='Path to graph')),
                ('labelsPath', models.FilePathField(default='~/labels.txt', max_length=250, verbose_name='Path to labels')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Graph created')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftUpperX', models.IntegerField()),
                ('leftUpperY', models.IntegerField()),
                ('rightUpperX', models.IntegerField()),
                ('rightUpperY', models.IntegerField()),
                ('rightLowerX', models.IntegerField()),
                ('rightLowerY', models.IntegerField()),
                ('leftLowerX', models.IntegerField()),
                ('leftLowerY', models.IntegerField()),
                ('rotation', models.FloatField(blank=True, null=True)),
                ('rotatedCordX', models.IntegerField(blank=True, null=True)),
                ('rotatedCordY', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorecognizer.Camera')),
            ],
        ),
    ]
