# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorecognizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='isStream',
            field=models.BooleanField(default=True, verbose_name='Is stream url for this camera stream.'),
        ),
    ]
